inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "spec/**/*"
    - "vendor/**/*"
    - "test/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "app/controllers/users/**/*"
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
